import { Patch, Style } from './types';

export const STYLES: Style[] = [
  {
    id: 'ambient',
    name: 'Ambient Drone',
    description: 'Nappes sonores évolutives, textures riches et reverb infinie.',
    icon: 'Cloud',
    patchId: 'patch_ambient',
    gradient: 'from-cyan-900 to-blue-950',
  },
  {
    id: 'techno',
    name: 'Techno Hypnotique',
    description: 'Riff répétitif, grosse caisse sourde et modulation lente.',
    icon: 'Zap',
    patchId: 'patch_techno',
    gradient: 'from-purple-900 to-slate-900',
  },
  {
    id: 'generative',
    name: 'Génératif Mélodique',
    description: 'Mélodies aléatoires qui ne se répètent jamais vraiment.',
    icon: 'Sparkles',
    patchId: 'patch_generative',
    gradient: 'from-emerald-900 to-slate-900',
  },
  {
    id: 'dark_ambient',
    name: 'Dark Ambient',
    description: 'Atmosphères sombres, drones inquiétants et bruits souterrains.',
    icon: 'Ghost',
    patchId: 'patch_dark_ambient',
    gradient: 'from-stone-900 to-black',
  },
  {
    id: 'glitch',
    name: 'Cyberpunk Glitch',
    description: 'Rythmes cassés, textures numériques et chaos contrôlé.',
    icon: 'Cpu',
    patchId: 'patch_glitch',
    gradient: 'from-cyan-900 to-slate-900',
  },
  {
    id: 'lofi',
    name: 'Lo-Fi Hip Hop',
    description: 'Beats détendus, souffle de bande et imperfections nostalgiques.',
    icon: 'Coffee',
    patchId: 'patch_lofi',
    gradient: 'from-orange-900 to-amber-950',
  },
  {
    id: 'psytrance',
    name: 'Psytrance Arp',
    description: 'Basses galopantes et arpèges acides rapides.',
    icon: 'Activity',
    patchId: 'patch_psytrance',
    gradient: 'from-fuchsia-900 to-purple-950',
  },
  {
    id: 'industrial',
    name: 'Industrial Percussion',
    description: 'Sons métalliques, distorsion lourde et rythmes mécaniques.',
    icon: 'Hammer',
    patchId: 'patch_industrial',
    gradient: 'from-red-950 to-stone-900',
  },
];

export const PATCHES: Record<string, Patch> = {
  patch_ambient: {
    id: 'patch_ambient',
    name: 'Ethereal Textures',
    description: 'Un patch classique pour créer des fonds sonores cinématiques utilisant la synthèse granulaire.',
    difficulty: 'Beginner',
    modules: [
      { name: 'VCO (Macro Oscillator 2)', type: 'Voice' },
      { name: 'LFO 1', type: 'Modulation' },
      { name: 'Attenuverter', type: 'Utility' },
      { name: 'Reverb (Plateau)', type: 'Effect' },
      { name: 'Audio Output', type: 'Output' },
    ],
    connections: [
      { from: 'LFO 1 [Sine]', to: 'Attenuverter [In]' },
      { from: 'Attenuverter [Out]', to: 'VCO [Timbre Mod]' },
      { from: 'VCO [Out]', to: 'Reverb [Input L]' },
      { from: 'VCO [Out]', to: 'Reverb [Input R]' },
      { from: 'Reverb [Out L]', to: 'Audio Output [L]' },
      { from: 'Reverb [Out R]', to: 'Audio Output [R]' },
    ],
    settings: [
      { module: 'VCO', parameter: 'Model', value: 'Granular (Cloud)' },
      { module: 'LFO 1', parameter: 'Frequency', value: '0.05 Hz' },
      { module: 'Attenuverter', parameter: 'Gain', value: '0.3' },
      { module: 'Reverb', parameter: 'Decay', value: '0.85' },
      { module: 'Reverb', parameter: 'Dry/Wet', value: '0.60' },
    ],
    tips: [
      "L'attenuverter est crucial pour que le LFO ne modifie pas le timbre trop brutalement.",
      "Essayez de changer le modèle du VCO vers 'Rings' (Cordes) pour une ambiance plus organique.",
    ],
  },
  patch_techno: {
    id: 'patch_techno',
    name: 'Rumble Kicks & Bleeps',
    description: 'La base de la Dub Techno avec un séquençage polyrythmique et un rumble de basse.',
    difficulty: 'Intermediate',
    modules: [
      { name: 'Clock Generator', type: 'Utility' },
      { name: 'Sequencer (Euclidean)', type: 'Sequencer' },
      { name: 'Kick Drum', type: 'Drums' },
      { name: 'FM Operator', type: 'Synth' },
      { name: 'Delay', type: 'Effect' },
      { name: 'Filter (High Pass)', type: 'Filter' },
      { name: 'Mixer', type: 'Utility' },
      { name: 'Audio Output', type: 'Output' },
    ],
    connections: [
      { from: 'Clock [Out]', to: 'Sequencer [Clock]' },
      { from: 'Sequencer [Gate 1]', to: 'Kick Drum [Trig]' },
      { from: 'Sequencer [Gate 2]', to: 'FM Operator [Gate]' },
      { from: 'Kick Drum [Out]', to: 'Mixer [Ch 1]' },
      // Rumble chain
      { from: 'Kick Drum [Out]', to: 'Filter [In]' },
      { from: 'Filter [Out]', to: 'Delay [In]' },
      { from: 'Delay [Out]', to: 'Mixer [Ch 2] (Rumble)' },
      
      { from: 'FM Operator [Out]', to: 'Mixer [Ch 3]' },
      { from: 'Mixer [Mix]', to: 'Audio Output [L]' },
      { from: 'Mixer [Mix]', to: 'Audio Output [R]' },
    ],
    settings: [
      { module: 'Sequencer', parameter: 'Steps 1', value: '4' },
      { module: 'Sequencer', parameter: 'Fill 1', value: '4' },
      { module: 'Sequencer', parameter: 'Steps 2', value: '16' },
      { module: 'Sequencer', parameter: 'Fill 2', value: '3' },
      { module: 'Delay', parameter: 'Time', value: '1/8' },
      { module: 'Delay', parameter: 'Feedback', value: '0.7' },
      { module: 'Filter', parameter: 'Cutoff', value: '150 Hz' },
    ],
    tips: [
      "Le 'Rumble' techno est créé en envoyant le Kick dans un Delay puis une Reverb (non listée ici pour simplifier), le tout filtré.",
      "Désaccordez légèrement l'opérateur FM pour un son plus industriel.",
    ],
  },
  patch_generative: {
    id: 'patch_generative',
    name: 'Marbles & Rings',
    description: 'Le duo classique du modulaire "West Coast" pour des sons organiques et boisés.',
    difficulty: 'Advanced',
    modules: [
      { name: 'Random Sampler (Marbles)', type: 'Sequencer' },
      { name: 'Resonator (Rings)', type: 'Voice' },
      { name: 'VCA', type: 'Utility' },
      { name: 'Reverb', type: 'Effect' },
      { name: 'Audio Output', type: 'Output' },
    ],
    connections: [
      { from: 'Marbles [t1]', to: 'Rings [Strum]' },
      { from: 'Marbles [X1]', to: 'Rings [V/Oct]' },
      // Modulation de timbre aléatoire
      { from: 'Marbles [X2]', to: 'Rings [Brightness]' },
      { from: 'Marbles [X3]', to: 'Rings [Damping]' },
      
      { from: 'Rings [Odd]', to: 'Reverb [Input L]' },
      { from: 'Rings [Even]', to: 'Reverb [Input R]' },
      { from: 'Reverb [Out L]', to: 'Audio Output [L]' },
      { from: 'Reverb [Out R]', to: 'Audio Output [R]' },
    ],
    settings: [
      { module: 'Marbles', parameter: 'Jitter', value: '12 o\'clock' },
      { module: 'Marbles', parameter: 'Scale', value: 'Major Pentatonic' },
      { module: 'Rings', parameter: 'Structure', value: 'Modal (Green)' },
      { module: 'Rings', parameter: 'Brightness', value: '0.4' },
      { module: 'Rings', parameter: 'Damping', value: '0.7' },
    ],
    tips: [
      "La sortie 't1' de Marbles génère le rythme, 'X1' génère la mélodie.",
      "Si le son est trop brillant, réduisez le bouton 'Brightness' sur Rings.",
    ],
  },
  patch_dark_ambient: {
    id: 'patch_dark_ambient',
    name: 'Abyssal Drones',
    description: 'Drones filtrés et texturés pour une atmosphère pesante.',
    difficulty: 'Intermediate',
    modules: [
      { name: 'VCO 1', type: 'Sound Source' },
      { name: 'VCO 2', type: 'Sound Source' },
      { name: 'VCF (Low Pass)', type: 'Filter' },
      { name: 'LFO 1 (Slow)', type: 'Modulation' },
      { name: 'Mixer', type: 'Utility' },
      { name: 'Delay', type: 'Effect' },
      { name: 'Reverb', type: 'Effect' },
      { name: 'Audio Output', type: 'Output' },
    ],
    connections: [
      { from: 'VCO 1 [Saw]', to: 'Mixer [Ch 1]' },
      { from: 'VCO 2 [Sine]', to: 'Mixer [Ch 2]' },
      { from: 'Mixer [Mix]', to: 'VCF [In]' },
      { from: 'LFO 1 [Triangle]', to: 'VCF [Cutoff CV]' },
      { from: 'VCF [Out]', to: 'Delay [In]' },
      { from: 'Delay [Out]', to: 'Reverb [In]' },
      { from: 'Reverb [Out]', to: 'Audio Output [L]' },
      { from: 'Reverb [Out]', to: 'Audio Output [R]' },
    ],
    settings: [
      { module: 'VCO 1', parameter: 'Pitch', value: '-24 Semi' },
      { module: 'VCO 2', parameter: 'Pitch', value: '-24.10 Semi (Detuned)' },
      { module: 'VCF', parameter: 'Resonance', value: '0.6' },
      { module: 'LFO 1', parameter: 'Rate', value: '0.05 Hz' },
      { module: 'Delay', parameter: 'Time', value: '1.5s' },
      { module: 'Reverb', parameter: 'Size', value: '0.9' },
    ],
    tips: [
      "Le désaccordage (Detune) entre les deux VCO est essentiel pour créer le 'battement' lent du drone.",
      "Ajoutez du Noise dans le VCF FM pour une texture plus sale.",
    ],
  },
  patch_glitch: {
    id: 'patch_glitch',
    name: 'Digital Chaos',
    description: 'Génération de textures IDM via modulation de fréquence aléatoire.',
    difficulty: 'Advanced',
    modules: [
      { name: 'Clock (Fast)', type: 'Utility' },
      { name: 'S&H (Sample & Hold)', type: 'Logic' },
      { name: 'Noise Generator', type: 'Source' },
      { name: 'Wavetable VCO', type: 'Synth' },
      { name: 'Envelope (AD)', type: 'Modulation' },
      { name: 'VCA', type: 'Utility' },
      { name: 'Bitcrusher', type: 'Effect' },
      { name: 'Audio Output', type: 'Output' },
    ],
    connections: [
      { from: 'Clock [Out]', to: 'S&H [Trig]' },
      { from: 'Clock [Out]', to: 'Envelope [Gate]' },
      { from: 'Noise [White]', to: 'S&H [In]' },
      
      // La magie du glitch : modulation aléatoire abrupte
      { from: 'S&H [Out]', to: 'Wavetable VCO [V/Oct]' },
      { from: 'S&H [Out]', to: 'Wavetable VCO [Position]' },
      
      { from: 'Wavetable VCO [Out]', to: 'VCA [In]' },
      { from: 'Envelope [Out]', to: 'VCA [CV]' },
      { from: 'VCA [Out]', to: 'Bitcrusher [In]' },
      { from: 'Bitcrusher [Out]', to: 'Audio Output [L]' },
      { from: 'Bitcrusher [Out]', to: 'Audio Output [R]' },
    ],
    settings: [
      { module: 'Clock', parameter: 'BPM', value: '300+' },
      { module: 'Envelope', parameter: 'Decay', value: '0.1s' },
      { module: 'Bitcrusher', parameter: 'Depth', value: '4 bit' },
      { module: 'Bitcrusher', parameter: 'Sample Rate', value: '2000 Hz' },
    ],
    tips: [
      "Le Sample & Hold capture le bruit aléatoire à chaque coup d'horloge, créant une tension aléatoire en escalier.",
      "Modulez le Sample Rate du Bitcrusher avec un LFO pour des variations vocales.",
    ],
  },
  patch_lofi: {
    id: 'patch_lofi',
    name: 'Dusty Tape Loop',
    description: 'Simulation de dérive de bande et de saturation.',
    difficulty: 'Intermediate',
    modules: [
      { name: 'Chord Oscillator', type: 'Synth' },
      { name: 'LFO 1 (Random)', type: 'Modulation' },
      { name: 'Low Pass Filter', type: 'Filter' },
      { name: 'Noise Generator', type: 'Source' },
      { name: 'Mixer', type: 'Utility' },
      { name: 'Audio Output', type: 'Output' },
    ],
    connections: [
      { from: 'LFO 1 [Out]', to: 'Chord Osc [Fine Tune] (Wow/Flutter)' },
      { from: 'Chord Osc [Out]', to: 'Filter [In]' },
      { from: 'Filter [Out]', to: 'Mixer [Ch 1]' },
      { from: 'Noise [Pink]', to: 'Mixer [Ch 2]' },
      { from: 'Mixer [Mix]', to: 'Audio Output [L]' },
      { from: 'Mixer [Mix]', to: 'Audio Output [R]' },
    ],
    settings: [
      { module: 'LFO 1', parameter: 'Rate', value: '0.2 Hz' },
      { module: 'LFO 1', parameter: 'Amount', value: 'Tiny (< 1%)' },
      { module: 'Filter', parameter: 'Cutoff', value: '600 Hz' },
      { module: 'Mixer', parameter: 'Ch 2 Level', value: '-24dB' },
      { module: 'Chord Osc', parameter: 'Chord', value: 'Minor 9' },
    ],
    tips: [
      "Le filtre doit être très fermé pour simuler une vieille cassette.",
      "Le bruit rose à très bas volume ajoute le 'hiss' caractéristique.",
    ],
  },
  patch_psytrance: {
    id: 'patch_psytrance',
    name: 'Alien Bassline',
    description: 'Le pattern de basse en triolet (K-B-B) typique de la Psytrance.',
    difficulty: 'Intermediate',
    modules: [
      { name: 'Saw Oscillator', type: 'Synth' },
      { name: 'Clock', type: 'Utility' },
      { name: 'Sequencer (16 step)', type: 'Sequencer' },
      { name: 'Filter (Acid)', type: 'Filter' },
      { name: 'Envelope (ADSR)', type: 'Modulation' },
      { name: 'VCA', type: 'Utility' },
      { name: 'Audio Output', type: 'Output' },
    ],
    connections: [
      { from: 'Clock [Out]', to: 'Sequencer [Clock]' },
      { from: 'Sequencer [Gate]', to: 'Envelope [Gate]' },
      { from: 'Sequencer [CV]', to: 'Oscillator [V/Oct]' },
      
      { from: 'Envelope [Out]', to: 'Filter [Cutoff CV]' },
      { from: 'Envelope [Out]', to: 'VCA [CV]' }, // VCA suit aussi l'enveloppe
      
      { from: 'Oscillator [Saw]', to: 'Filter [In]' },
      { from: 'Filter [Out]', to: 'VCA [In]' },
      { from: 'VCA [Out]', to: 'Audio Output [L]' },
      { from: 'VCA [Out]', to: 'Audio Output [R]' },
    ],
    settings: [
      { module: 'Sequencer', parameter: 'Grid', value: '1/16T (Triplet)' },
      { module: 'Sequencer', parameter: 'Gates', value: '1-0-1-1-0-1 (K-B-B)' },
      { module: 'Filter', parameter: 'Resonance', value: '0.7' },
      { module: 'Envelope', parameter: 'Decay', value: '0.15s (Snappy)' },
      { module: 'Envelope', parameter: 'Sustain', value: '0' },
    ],
    tips: [
      "C'est l'interaction entre le Decay de l'enveloppe et la Cutoff du filtre qui crée le son 'élastique'.",
      "La note fondamentale ne change presque pas, c'est le rythme qui compte.",
    ],
  },
  patch_industrial: {
    id: 'patch_industrial',
    name: 'Factory Floor',
    description: 'Percussions métalliques utilisant la synthèse FM et la distorsion.',
    difficulty: 'Advanced',
    modules: [
      { name: 'Clock', type: 'Utility' },
      { name: 'Noise Generator', type: 'Source' },
      { name: 'VCO (Carrier)', type: 'Synth' },
      { name: 'VCO (Modulator)', type: 'Synth' },
      { name: 'VCA', type: 'Utility' },
      { name: 'Envelope (AD)', type: 'Modulation' },
      { name: 'Distortion', type: 'Effect' },
      { name: 'Audio Output', type: 'Output' },
    ],
    connections: [
      { from: 'Clock [Out]', to: 'Envelope [Gate]' },
      
      // FM Setup
      { from: 'VCO Modulator [Sine]', to: 'VCA [In]' }, // Modulator passes through VCA
      { from: 'Envelope [Out]', to: 'VCA [CV]' }, // Envelope shapes Modulator amount
      { from: 'VCA [Out]', to: 'VCO Carrier [FM Input]' },
      
      { from: 'VCO Carrier [Triangle]', to: 'Distortion [In]' },
      { from: 'Distortion [Out]', to: 'Audio Output [L]' },
      { from: 'Distortion [Out]', to: 'Audio Output [R]' },
    ],
    settings: [
      { module: 'VCO Carrier', parameter: 'Freq', value: '100 Hz' },
      { module: 'VCO Modulator', parameter: 'Freq', value: '243 Hz (Ratio 2.43)' },
      { module: 'Distortion', parameter: 'Drive', value: '0.9' },
      { module: 'Envelope', parameter: 'Decay', value: '0.3s' },
    ],
    tips: [
      "Utilisez un ratio de fréquence non-entier (ex: 2.43) entre les oscillateurs pour des sons métalliques.",
      "La distorsion agit comme un compresseur et fait ressortir les harmoniques aiguës.",
    ],
  },
};